// Generated by CoffeeScript 1.3.1
(function() {
  var Pie;

  Pie = (function() {

    Pie.name = 'Pie';

    function Pie(attributes) {
      var key, value;
      for (key in attribute) {
        value = attribute[key];
        this[key] = value;
      }
      this.setDefaults();
      this;

    }

    Pie.prototype.setDefaults = function() {
      if (!this.state) {
        this.state = 'inactive';
      }
      return this.generateId();
    };

    return Pie;

  })();

  module.exports = Pie;

}).call(this);
